### ISSUE TITLE
Do you test it between clouds server and your client？

### ISSUE THREAD

**Issue by yyLeeShine** [shrikrishnalolla/MPQUIC_streaming#1]
I have tested your code and find a problem,the client has two ips and the server is one, but when i tested it, lots of udp packets were sent through one ip of the client and a few udp packets were sent through the other ip. so the aggregated output is quite low,Do you test it between the clouds server and your client or you just test it locally ? Have you found this problem?

**Comment by shrikrishnalolla** [comment]
Hi,
The testing was conducted locally. Unfortunately, I did not have any access to a cloud server, due to which I did not come across this issue. Do the paths from the client have very different speeds? You could try throttling the bandwidth or introduce packet drop in the faster connection to obtain better results.

**Comment by yyLeeShine** [comment]
thanks for your reply，i doubt the mpquic code has some bugs，so i hope this problem can be solved
